version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: lovelystay_postgres_container
    environment:
      POSTGRES_USER: lovelystay_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lovelystay_localhost_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
